apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-quality-agent
spec:
  replicas: 3
  template:
    spec:
      containers:
      - name: agent
        image: data-quality-agent:latest
        env:
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: api-secrets
              key: openai-api-key
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"